### ISSUE TITLE
udp2raw进程会被互杀

### ISSUE THREAD

**Issue by keeno1982** [hongwenjun/openwrt-luci-kcp-udp#1]
看起来这个工具是可以同时跑两个udp2raw进程的，但是当在工具中重启udptool或者kcptool时就会将另一个进程的udp2raw给杀掉，做不到各自独立，希望能改进一下，不然就失去 kcptool和udptool同时加速的初衷，比较可惜

另外希望能加入多个服务器的选择，并且能将init.d里面的配置文件放到界面上编辑，感谢！

**Comment by hongwenjun** [comment]
我也是修改别人的插件，添加功能，虽然可以修改成同时运行，但是作用并不大。
（修改成同时运行，就是把 udp2raw 复制或者软链接一份 为 udp2raw_copy   ，然后修改辅助的哪个工具的启动和杀进程语句 ）

所以我后来添加了这个脚本，openwrt 和 其他 linux debian arch 都可以用的直接脚本运行
https://git.io/sskcp.sh
