### ISSUE TITLE
luci-udptool安装后找不到入口

### ISSUE THREAD

**Issue by xspeed1989** [hongwenjun/openwrt-luci-kcp-udp#2]
luci-udptool安装后找不到入口

**Comment by hongwenjun** [comment]
这个是webui设置，软件需要另外装的
推荐使用这个脚本，路由器和linux系统都可以用
https://git.io/sskcp.sh

**Comment by xspeed1989** [comment]
找到了， 网络下面，
我只用speeder，写了个开机启动脚本，没有用WebUI

蘭雅sRGB ***@***.***> 于2021年11月15日周一 上午9:30写道：
